name: npm-pack
inputs:
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  outdir:
    description: package spec (path to package.json)
    type: string
    required: false
    default: ./
outputs:
  json:
    description: JSON output of npm-pack
    value: ${{ steps.npm-pack.outputs.packjson }}
  package:
    description: package name (without path)
    value: ${{ steps.npm-pack.outputs.package }}
  package-full:
    description: package name with path
    value: ${{ steps.npm-pack.outputs.package_full }}
  contents:
    description: package contents (tar tvf)
    value: ${{ steps.list-contents.outputs.contents }}
runs:
  using: composite
  steps:
  - shell: bash
    run: |-
      mkdir -p {{ inputs.outdir }}
  - id: npm-pack
    shell: bash
    run: |-
      packjson=$(npm pack ${{ inputs.spec }} --pack-destination ${{ inputs.outdir }} --json)
      filename=$(echo ${packjson} | jq -e ".[0].filename" -r)
      ls ${{ inputs.outdir }}/${filename}
      echo "package=${filename}" >> GITHUB_OUTPUT
      echo "package_full=${{ inputs.outdir }}/${filename}" >> GITHUB_OUTPUT
      echo "packjson=${packjson}" >> GITHUB_OUTPUT
  - id: list-contents
    shell: bash
    run: |
      contents=$(tar tvf ${{ steps.npm-pack.outputs.package_full }})
      echo ${contents}
      echo "contents=${contents}" >> GITHUB_OUTPUT
