name: npm-metagen
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  seed:
    description: seed for Metagen
    type: string
    required: false
    default: ${{ github.repository }}
runs:
  using: composite
  steps:
  - id: npm-pack-dryrun
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      pushd $(dirname ${{ inputs.spec }})
      packjson=$(npm pack --pack-destination ${{ inputs.outdir }} --json --dry-run | jq -cM)
      filename=$(echo ${packjson} | jq -e ".[0].filename" -r)
      files=$(echo ${packjson}    | jq -e ".[0].files[].path" -r)

      echo "packjson: ${packjson}"
      echo "filename: ${filename}"
      echo "files: ${files}"

      echo "package=${filename}" >> $GITHUB_OUTPUT
      echo "package_full=${{ inputs.outdir }}/${filename}" >> $GITHUB_OUTPUT
      echo "packjson=\'${packjson}\'" >> $GITHUB_OUTPUT
      echo "files=\'${files}\'" >> $GITHUB_OUTPUT
      popd
      popd
  - shell: bash
    run: |-
      echo "package: ${{ steps.npm-pack-dryrun.outputs.package }}"
      echo "package_full: ${{ steps.npm-pack-dryrun.outputs.package_full }}"
      echo "packjson: ${{ steps.npm-pack-dryrun.outputs.packjson }}"
      echo "files: ${{ steps.npm-pack-dryrun.outputs.files }}"
  - id: metagen-files
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      pushd $(dirname ${{ inputs.spec }})
      allfiles="${{ steps.npm-pack-dryrun.outputs.files }}"
      echo "allfiles: ${allfiles}"

      notmetafiles=$(echo ${allfiles} | rg -v "((\.meta$))")
      echo "notmetafiles: ${notmetafiles}"

      for a in $(echo ${notmetafiles}); do
        if [ ! -f "$a.meta" ]; then
          metagen -s ${{ inputs.seed }} $a
        fi
      done
      popd
      popd
