name: npm-add-registry
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  config-file:
    description: npmrc file (defaults to '.npmrc')
    type: string
    required: false
    default: .npmrc
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  registry:
    description: full registry URL including 'https://' and '@scope'
    required: false
    default: https://npm.pkg.github.com/@${{ github.repository_owner }}
  token:
    description: NPM registry token (e.g. GitHub token with package.write)
    required: true
outputs:
  registry:
    description: parsed registry
    value: ${{ steps.parse-registry.outputs.registry }}
  scope:
    description: parsed scope
    value: ${{ steps.parse-registry.outputs.scope }}
runs:
  using: composite
  steps:
  - shell: pwsh
    run: |-
      throw 'This action is deprecated. Please use actions/setup-node instead'
