name: [NPM] Patch package.json .files
description: Modifies the .files element of the given package.json spec

inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  patch:
    description: new contents for .files element
    type: string
    required: true

runs:
  using: composite
  steps:
  - name: Apply
    uses: kagekirin/gha-npm/.github/actions/json-patch-element@main
    with:
      path: ${{ inputs.path }}
      file: ${{ inputs.spec }}
      element: '.files'
      value: ${{ inputs.patch }}
