name: npm-patch-spec-files
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  patch:
    description: patch for package spec to overwrite .files
    type: string
    required: true
runs:
  using: composite
  steps:
  - name: Show patch
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      cat ${{ inputs.patch }}
      popd
  - name: Before patch
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      cat ${{ inputs.spec }}
      popd
  - name: Patch
    id: patch
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      contents="$(jq --argjson v "$(cat ${{ inputs.patch }})" '.files = $v' ${{ inputs.spec }})"
      echo -E "${contents}" > ${{ inputs.spec }}
      popd
  - name: After patch
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      cat ${{ inputs.spec }}
      popd
