name: npm-patch-spec-files
inputs:
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  patch:
    description: patch for package spec to overwrite .files
    type: string
    required: true
runs:
  using: composite
  steps:
  - id: patch
    shell: bash
    run: |-
      packjson=$(npm pack ${{ inputs.spec }} --pack-destination ${{ inputs.outdir }} --json --dry-run)
      filename=$(echo ${packjson} | jq -e ".[0].filename" -r)
      files=$(echo ${packjson}    | jq -e ".[0].files[].path" -r)
      echo "package=${filename}" >> GITHUB_OUTPUT
      echo "package_full=${{ inputs.outdir }}/${filename}" >> GITHUB_OUTPUT
      echo "packjson=${packjson}" >> GITHUB_OUTPUT
      echo "files=${files}" >> GITHUB_OUTPUT
  - id: metagen-files
    shell: bash
    run: |-
      pushd $(dirname ${{ inputs.spec }})
      notmetafiles=$(echo "${{ steps.npm-pack-dryrun.outputs.files }}" | rg -v "((\.meta$))")
      for a in $(echo notmetafiles); do
        if [ ! -f "$a.meta" ]; then
          metagen -s ${{ inputs.seed }} $a
        fi
      done
      popd
