name: [NPM] Publish packages
description: Publishes a pre-packed package

inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  package:
    description: package path (.tgz file)
    type: string
    required: true
  access:
    description: package access
    type: string
    required: false
    default: public
  dry-run:
    description: whether to perform a dry-run
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
  - id: npm-publish-package
    shell: pwsh
    run: |-
      Push-Location ${{ inputs.path }}
      Push-Location (Split-Path -Path ${{ inputs.package }})

      $package = (Split-Path -Path ${{ inputs.package }} -Leaf -Resolve)
      if ([string]::IsNullOrEmpty($package))
      {
        throw 'No package file provided'
      }

      cat .npmrc
      if ($${{ inputs.dry-run }})
      {
        echo "npm publish $package --access=${{ inputs.access }} --verbose --dry-run"
        npm publish $package --access=${{ inputs.access }} --verbose --dry-run
      }
      else
      {
        echo "npm publish $package --access=${{ inputs.access }} --verbose"
        npm publish $package --access=${{ inputs.access }} --verbose
      }

      Pop-Location
      Pop-Location
