name: [NPM] Publish packages
description: Publishes a pre-packed package

inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  package:
    description: package path (.tgz file)
    type: string
    required: true
  registry:
    description: registry URL
    type: string
    required: true
  access:
    description: package access
    type: string
    required: false
    default: public
  dry-run:
    description: whether to perform a dry-run
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
  - id: npm-publish-package
    shell: pwsh
    run: |-
      Push-Location ${{ inputs.path }}

      $registry = "${{ inputs.registry }}".ToLower()
      $registryUrl = $registry.Split("@")[0]
      $package  = "${{ inputs.package }}"

      if ([string]::IsNullOrEmpty($package))
      {
        throw 'No package file supplied'
      }

      Write-Output "publishing $package to $registry"

      cat .npmrc
      if ($${{ inputs.dry-run }})
      {
        Write-Output "npm publish $package --access=${{ inputs.access }} --verbose --dry-run --registry=$registryUrl"
        npm publish $package --access=${{ inputs.access }} --verbose --dry-run --registry=$registryUrl
      }
      else
      {
        Write-Output "npm publish $package --access=${{ inputs.access }} --verbose --registry=$registryUrl"
        npm publish $package --access=${{ inputs.access }} --verbose --registry=$registryUrl
      }

      Pop-Location
