name: '[NPM] Publish'
description: Builds and publishes a package given its specfile (package.json)

inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  access:
    description: package access
    type: string
    required: false
    default: public
  dry-run:
    description: whether to perform a dry-run
    type: boolean
    required: false
    default: false
  token:
    description: NPM registry token required for publishing
    type: string
    required: true

runs:
  using: composite
  steps:
  - name: 'NPM Publish'
    id: npm-publish
    shell: pwsh
    env:
      NODE_AUTH_TOKEN: ${{ inputs.token }}
    run: |-
      Push-Location ${{ inputs.path }}
      Push-Location (Split-Path -Path ${{ inputs.spec }})

      $spec = (Split-Path -Path ${{ inputs.spec }} -Leaf -Resolve)
      if ([string]::IsNullOrEmpty($spec))
      {
        throw 'No spec file provided'
      }

      cat .npmrc
      if ($${{ inputs.dry-run }})
      {
        echo "npm publish --access=${{ inputs.access }} --verbose --dry-run"
        npm publish --access=${{ inputs.access }} --verbose --dry-run
      }
      else
      {
        echo "npm publish --access=${{ inputs.access }} --verbose"
        npm publish --access=${{ inputs.access }} --verbose
      }

      Pop-Location
      Pop-Location
