name: npm-publish
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  access:
    description: package access
    type: string
    required: false
    default: public
  dry-run:
    description: whether to perform a dry-run
    type: boolean
    default: false
runs:
  using: composite
  steps:
  - id: npm-publish
    shell: pwsh
    run: |-
      Push-Location ${{ inputs.path }}
      Push-Location (Split-Path -Path ${{ inputs.spec }})

      $dryrun = ($${{ inputs.dry-run }}) ? '--dry-run' : ''
      Write-Output "dryrun: $dryrun"

      cat ${{ inputs.spec }} | jq
      cat ${{ inputs.spec }} | jq -r '.publishConfig.registry'
      $registry=(cat ${{ inputs.spec }} | jq -r '.publishConfig.registry')
      Write-Output "publishing to ${registry}"

      cat .npmrc
      Write-Output "npm publish --access=${{ inputs.access }} --verbose $dryrun --registry=$registry"
      npm publish --access=${{ inputs.access }} --verbose $dryrun --registry=$registry

      Pop-Location
      Pop-Location
