name: [NPM] Publish
description: Builds and publishes a package given its specfile (package.json)

inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  spec:
    description: package spec (path to package.json)
    type: string
    required: false
    default: package.json
  access:
    description: package access
    type: string
    required: false
    default: public
  dry-run:
    description: whether to perform a dry-run
    type: boolean
    default: false
runs:
  using: composite
  steps:
  - id: npm-publish
    shell: pwsh
    run: |-
      Push-Location ${{ inputs.path }}
      Push-Location (Split-Path -Path ${{ inputs.spec }})

      cat ${{ inputs.spec }} | jq
      cat ${{ inputs.spec }} | jq -r '.publishConfig.registry'
      $registry=(cat ${{ inputs.spec }} | jq -r '.publishConfig.registry')
      $registryUrl = $registry.Split("@")[0]
      Write-Output "publishing to ${registry}"

      cat .npmrc
      if ($${{ inputs.dry-run }})
      {
        Write-Output "npm publish --access=${{ inputs.access }} --verbose --dry-run --registry=$registryUrl"
        npm publish --access=${{ inputs.access }} --verbose --dry-run --registry=$registryUrl
      }
      else
      {
        Write-Output "npm publish --access=${{ inputs.access }} --verbose --registry=$registryUrl"
        npm publish --access=${{ inputs.access }} --verbose --registry=$registryUrl

      }

      Pop-Location
      Pop-Location
